name: Upload to AUR

on: workflow_call

jobs:
  upload_aur:
    environment: Main
    name: Upload to AUR
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v4
        with:
          path: ./mainRepo
          fetch-depth: 0

      - uses: actions/download-artifact@v3
        with:
          path: ./

      - name: Import SSH key
        id: key
        run: |
          echo "Importing SSH ley..."
          mkdir ~/.ssh
          # echo "${secrets.SSH_PRIVATE_KEY}" > ~/.ssh/id_rsa
          echo "$SSH_KEY" | base64 -d > ~/.ssh/id_rsa
          echo "Updating ~/.ssh/known_hosts..."
          ssh-keyscan aur.archlinux.org >> ~/.ssh/known_hosts
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_rsa
          ls -la ~/.ssh
          cat ~/.ssh/id_rsa
          echo "Step completed"
        env:
          SSH_KEY: ${{ secrets.ID_RSA }}

      - name: Publish AUR
        id: figma-linux-actions
        uses: ./mainRepo
        with:
          action: publish_aur_git
          token: ${{ secrets.GITHUB_TOKEN }}
